AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal AWS IoT Core setup for a PM500 device with least-privilege policy.

Parameters:
  ThingName:
    Type: String
    Description: Name of the IoT thing.
  PolicyName:
    Type: String
    Description: Name of the IoT policy.
  AllowedTopicArns:
    Type: CommaDelimitedList
    Description: Comma-delimited list of full topic or topic filter ARNs the device may access.

Resources:
  IoTThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: !Ref ThingName

  IoTCertificate:
    Type: AWS::IoT::Certificate
    Properties:
      Status: ACTIVE
    Metadata:
      Comment: Export the certificate and private key as soon as the stack completes; store securely and rotate regularly.

  IoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyName: !Ref PolicyName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - iot:Connect
            Resource: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:client/${ThingName}
          - Effect: Allow
            Action:
              - iot:Publish
              - iot:Subscribe
              - iot:Receive
            Resource: !Ref AllowedTopicArns

  ThingCertificateAttachment:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      ThingName: !Ref IoTThing
      Principal: !GetAtt IoTCertificate.Arn

  PolicyAttachment:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      PolicyName: !Ref IoTPolicy
      Principal: !GetAtt IoTCertificate.Arn

Outputs:
  CertificatePem:
    Description: PEM-encoded certificate. Handle as sensitive output.
    Value: !GetAtt IoTCertificate.CertificatePem
    Export:
      Name: !Sub ${AWS::StackName}-CertificatePem
  PrivateKey:
    Description: Private key for the certificate. Protect it using secrets management or HSM.
    Value: !GetAtt IoTCertificate.PrivateKey
    Export:
      Name: !Sub ${AWS::StackName}-PrivateKey
  CertificateArn:
    Description: ARN of the active certificate.
    Value: !GetAtt IoTCertificate.Arn

